### ISSUE TITLE
Fix docs build

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#120]
- [x] Read the Docs theme must be a dependency
- [ ] Warnings on @beraldoleal's screen

**Comment by cemsbr** [comment]
@beraldoleal , I can't see those errors anymore. Could you make sure you are using python 3 (virtualenv3, pip3) and paste the output, please?

**Comment by beraldoleal** [comment]
```
root@sdn-dev:/var/www/docs/repos/python-openflow# cd docs/
root@sdn-dev:/var/www/docs/repos/python-openflow/docs# make html
sphinx-apidoc -o . ../pyof/ -d10 -M
File ./pyof.rst already exists, skipping.
File ./pyof.v0x01.rst already exists, skipping.
File ./pyof.v0x01.asynchronous.rst already exists, skipping.
File ./pyof.v0x01.common.rst already exists, skipping.
File ./pyof.v0x01.controller2switch.rst already exists, skipping.
File ./pyof.v0x01.foundation.rst already exists, skipping.
File ./pyof.v0x01.symmetric.rst already exists, skipping.
File ./pyof.v0x02.rst already exists, skipping.
File ./pyof.v0x02.common.rst already exists, skipping.
File ./modules.rst already exists, skipping.
sed -i "/Submodules/,+1d" *.rst
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.5
loading pickled environment... done
loading intersphinx inventory from python.inv...
WARNING: intersphinx inventory 'python.inv' not fetchable due to <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/var/www/docs/repos/python-openflow/docs/python.inv'
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 11 source files that are out of date
updating environment: 0 added, 11 changed, 0 removed
reading sources... [  9%] index
reading sources... [ 18%] modules
reading sources... [ 27%] pyof
reading sources... [ 36%] pyof.v0x01
reading sources... [ 45%] pyof.v0x01.asynchronous
reading sources... [ 54%] pyof.v0x01.common
reading sources... [ 63%] pyof.v0x01.controller2switch
reading sources... [ 72%] pyof.v0x01.foundation
reading sources... [ 81%] pyof.v0x01.symmetric
reading sources... [ 90%] pyof.v0x02
reading sources... [100%] pyof.v0x02.common

../README.rst:4: WARNING: nonlocal image URI found: https://img.shields.io/badge/Openflow-1.0.0-brightgreen.svg
../README.rst:4: WARNING: nonlocal image URI found: https://img.shields.io/github/tag/kytos/python-openflow.svg
../README.rst:4: WARNING: nonlocal image URI found: https://img.shields.io/github/release/kytos/python-openvpn.svg
../README.rst:4: WARNING: nonlocal image URI found: http://kytos.io/imgs/tests-status.svg
../README.rst:4: WARNING: nonlocal image URI found: https://img.shields.io/github/license/kytos/python-openflow.svg
../README.rst:74: WARNING: nonlocal image URI found: https://img.shields.io/badge/Openflow-1.0.0-brightgreen.svg
../README.rst:76: WARNING: nonlocal image URI found: https://img.shields.io/github/tag/kytos/python-openflow.svg
../README.rst:78: WARNING: nonlocal image URI found: https://img.shields.io/github/release/kytos/python-openvpn.svg
../README.rst:80: WARNING: nonlocal image URI found: http://kytos.io/imgs/tests-status.svg
../README.rst:82: WARNING: nonlocal image URI found: https://img.shields.io/github/license/kytos/python-openflow.svg
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:13: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.aggregate_stats_reply'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.aggregate_stats_reply'
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:21: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.aggregate_stats_request'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.aggregate_stats_request'
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:53: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.desc_stats'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.desc_stats'
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:85: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.flow_stats'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.flow_stats'
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:93: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.flow_stats_request'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.flow_stats_request'
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:133: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.port_stats'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.port_stats'
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:141: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.port_stats_request'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.port_stats_request'
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:165: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.queue_stats'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.queue_stats'
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:173: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.queue_stats_request'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.queue_stats_request'
/var/www/docs/repos/python-openflow/docs/pyof.v0x01.controller2switch.rst:205: WARNING: autodoc: failed to import module 'pyof.v0x01.controller2switch.table_stats'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x01.controller2switch.table_stats'
/var/www/docs/repos/python-openflow/docs/pyof.v0x02.common.rst:13: WARNING: autodoc: failed to import module 'pyof.v0x02.common.flow_instruction'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
ImportError: No module named 'pyof.v0x02.common.flow_instruction'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... WARNING: search index couldn't be loaded, but not all documents will be built: the index will be incomplete.
done
writing output... [  9%] index
writing output... [ 18%] modules
writing output... [ 27%] pyof
writing output... [ 36%] pyof.v0x01
writing output... [ 45%] pyof.v0x01.asynchronous
writing output... [ 54%] pyof.v0x01.common
writing output... [ 63%] pyof.v0x01.controller2switch
writing output... [ 72%] pyof.v0x01.foundation
writing output... [ 81%] pyof.v0x01.symmetric
writing output... [ 90%] pyof.v0x02
writing output... [100%] pyof.v0x02.common

generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 23 warnings.

Build finished. The HTML pages are in _build/html.
```

**Comment by cemsbr** [comment]
It might be the 3.4 Python version, because the HACKING file states that we use Python 3.5. I'll test it in a clean VM to be sure (I've already tested with virtualenv).

**Comment by beraldoleal** [comment]
We were using python3.5 because of asyncio. But now I don't see any reason for this restriction.

But since that the next Ubuntu LTS will be available in few days, I think that it is ok if we put this in hold for a while. @cemsbr, do you see any reason that we are requiring python 3.5 ?

**Comment by cemsbr** [comment]
I confirmed that it works in a clean Ubuntu 16.04 install.

I cannot guarantee we are 100% compatible with Python 3.4. To be sure, we must run the tests with this other version. Continuous Integration systems like travis can run the tests with multiple Python versions (3.5, 3.4, 3.3, ...). I'm not sure whether it is worth it, since everything tends to run isolated in a VM/container nowadays, where it is possible to install the latest Python version.

I'm closing for now. If there is a need for Python < 3.5 support, we discuss it later.

**Comment by beraldoleal** [comment]
The ubuntu running on error is 16.04. 16.04 has python 3.4.

I will reopen. but dont worry, is only to not loose track of this.
