### ISSUE TITLE
ErrorMsg unpacking error

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/python-openflow#364]
As presented in kytos/kytos-napps#226, there is an exception raised when unpacking asynchronous Error Messages coming from switches.

```
Traceback (most recent call last):
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/foundation/base.py", line 193, in unpack
    self._value = self.enum_ref(self._value)
  File "/usr/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 2 is not a valid Port

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/kytos-2017.1b2.post2-py3.6.egg/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "/home/renan/testes/asd/var/lib/kytos/napps/kytos/of_core/main.py", line 126, in handle_new_openflow_message
    message.unpack(binary_data)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/v0x01/asynchronous/error_msg.py", line 209, in unpack
    self.data = self._unpack_data()
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/v0x01/asynchronous/error_msg.py", line 223, in _unpack_data
    msg.unpack(msg_data)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/v0x01/controller2switch/packet_out.py", line 101, in unpack
    attribute.unpack(buff, begin)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/foundation/base.py", line 197, in unpack
    raise UnpackException(msg)
pyof.foundation.exceptions.UnpackException: 2 is not a valid Port; fmt = !H, buff = b'\x00\x00\x01X\x00\x02\x00\x08\x00\x00\x00\x08\x00\x01\xff\xff\xda\x19\x106\xbb6\x12\x88\xa3\xc9LU\x08\x06\x00\x01\x08.
```

**Comment by erickvermot** [comment]
This is a problem with pyof.asunchronous.error_msg ErrorMsg.
As the spec says about ErrorMsg.data:
"The data is variable length and interpreted based on the type and code; in most cases this is the message that caused the problem"

but the error_msg.py ErrorMsg.unpack method always tries to unpack the data. This may lead to 2 problems:
1 - The data does not correspond to a msg
2 - The original message which originated the error is invalid/corrupt, so trying to unpack it will lead to an UnpackException.

Solutions could be:
1 - Not unpack the data, and live it in binary for for debugging.
2 - Verify that this is a ErrorMsg code that contains a packet in the data attribute, and Try / Except unpacking the data, and only print the error for debugging.

**Comment by erickvermot** [comment]
There is also another problem that affect this case.
PacketOut.in_port uses Port (defined at common/phy_port.py) as a enum_ref for the UBInt16:
``in_port = UBInt16(enum_ref=Port)`` - pyof/controller2switch/packet_out.py line 25, but can obviously assume values other than those listed in the Port enum, leading to the UnpackError of the PacketOut.
