### ISSUE TITLE
Asynchronous ErrorMsg packets are being incorrectly unpacked

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/python-openflow#367]
When the controller receives an error from any switch, the unpack is being done the wrong way.
As noted, the problem is when unpacking in the `data` field, which can be different depending on the error's type and code.

```
Exception in thread Thread-21761:
Traceback (most recent call last):
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/foundation/base.py", line 191, in unpack
    self._value = struct.unpack_from(self._fmt, buff, offset)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/foundation/base.py", line 573, in _unpack_attribute
    attribute.unpack(buff, begin)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/foundation/base.py", line 197, in unpack
    raise UnpackException(msg)
pyof.foundation.exceptions.UnpackException: unpack_from requires a buffer of at least 4 bytes; fmt = !I, buff = b'\x00?\xff\xe3\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', offset = 56.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/kytos-2017.1b2.post2-py3.6.egg/kytos/core/helpers.py", line 68, in threaded_handler
    handler(*args)
  File "/home/renan/testes/asd/var/lib/kytos/napps/kytos/of_core/main.py", line 126, in handle_new_openflow_message
    message.unpack(binary_data)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/v0x01/asynchronous/error_msg.py", line 209, in unpack
    self.data = self._unpack_data()
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/v0x01/asynchronous/error_msg.py", line 223, in _unpack_data
    msg.unpack(msg_data)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/foundation/base.py", line 755, in unpack
    size = self._unpack_attribute(name, value, buff, begin)
  File "/home/renan/testes/asd/lib/python3.6/site-packages/pyof/foundation/base.py", line 578, in _unpack_attribute
    raise UnpackException(msg)
pyof.foundation.exceptions.UnpackException: FlowMod.buffer_id; unpack_from requires a buffer of at least 4 bytes; fmt = !I, buff = b'\x00?\xff\xe3\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', offset = 56.
```

**Comment by erickvermot** [comment]
for future reference:
https://github.com/kytos/python-openflow/issues/364#issuecomment-300503579
